apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend-deployment
        image: saikarthik28/python-todo-backend
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
          - name: DB_HOST
            value: db-service         
          - name: DB_NAME
            value: todo_db            
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials-secret 
                key: DB_PASSWORD